import os
import shutil
import zipfile
from pathlib import Path

# ── PATHS ─────────────────────────────────────────────────────────────
TRAINING_DIR   = r"D:\Coding Section\Mediscan\training"
ZIP_FILE       = os.path.join(TRAINING_DIR, "MediScan Strip Detection.yolov8.zip")
EXTRACT_DIR    = os.path.join(TRAINING_DIR, "roboflow_extracted")
AUGMENTED_DIR  = os.path.join(TRAINING_DIR, "augmented_yolo")
FINAL_DIR      = os.path.join(TRAINING_DIR, "final_dataset")

# ── STEP 1: Extract the zip ───────────────────────────────────────────
print("Step 1: Extracting zip file...")
os.makedirs(EXTRACT_DIR, exist_ok=True)
with zipfile.ZipFile(ZIP_FILE, 'r') as z:
    z.extractall(EXTRACT_DIR)
print(f"  Extracted to: {EXTRACT_DIR}")

# ── STEP 2: Create final dataset folder structure ─────────────────────
print("\nStep 2: Creating final dataset structure...")
for split in ['train', 'valid', 'test']:
    os.makedirs(os.path.join(FINAL_DIR, split, 'images'), exist_ok=True)
    os.makedirs(os.path.join(FINAL_DIR, split, 'labels'), exist_ok=True)

# ── HELPER: copy images + labels from one folder to another ───────────
def copy_split(src_images, src_labels, dst_images, dst_labels, prefix=""):
    copied = 0
    if not os.path.exists(src_images):
        print(f"  Warning: folder not found: {src_images}")
        return 0
    for img_file in os.listdir(src_images):
        if not img_file.lower().endswith(('.jpg', '.jpeg', '.png')):
            continue
        stem = Path(img_file).stem
        src_img = os.path.join(src_images, img_file)
        src_lbl = os.path.join(src_labels, stem + '.txt')

        # Add prefix to avoid filename collisions
        new_name = prefix + img_file
        new_stem = prefix + stem
        shutil.copy2(src_img, os.path.join(dst_images, new_name))
        if os.path.exists(src_lbl):
            shutil.copy2(src_lbl, os.path.join(dst_labels, new_stem + '.txt'))
        else:
            # Create empty label file if missing
            open(os.path.join(dst_labels, new_stem + '.txt'), 'w').close()
        copied += 1
    return copied

# ── STEP 3: Copy augmented_yolo → final_dataset/train ─────────────────
print("\nStep 3: Copying augmented YOLO images → train...")
n = copy_split(
    src_images = os.path.join(AUGMENTED_DIR, 'images'),
    src_labels = os.path.join(AUGMENTED_DIR, 'labels'),
    dst_images = os.path.join(FINAL_DIR, 'train', 'images'),
    dst_labels = os.path.join(FINAL_DIR, 'train', 'labels'),
    prefix     = "aug_"
)
print(f"  Copied {n} augmented images")

# ── STEP 4: Copy Roboflow train → final_dataset/train ─────────────────
print("\nStep 4: Copying Roboflow train images → train...")
n = copy_split(
    src_images = os.path.join(EXTRACT_DIR, 'train', 'images'),
    src_labels = os.path.join(EXTRACT_DIR, 'train', 'labels'),
    dst_images = os.path.join(FINAL_DIR, 'train', 'images'),
    dst_labels = os.path.join(FINAL_DIR, 'train', 'labels'),
    prefix     = "rf_"
)
print(f"  Copied {n} Roboflow train images")

# ── STEP 5: Copy Roboflow valid → final_dataset/valid ─────────────────
print("\nStep 5: Copying Roboflow valid images → valid...")
n = copy_split(
    src_images = os.path.join(EXTRACT_DIR, 'valid', 'images'),
    src_labels = os.path.join(EXTRACT_DIR, 'valid', 'labels'),
    dst_images = os.path.join(FINAL_DIR, 'valid', 'images'),
    dst_labels = os.path.join(FINAL_DIR, 'valid', 'labels'),
    prefix     = "rf_"
)
print(f"  Copied {n} Roboflow valid images")

# ── STEP 6: Copy Roboflow test → final_dataset/test ───────────────────
print("\nStep 6: Copying Roboflow test images → test...")
n = copy_split(
    src_images = os.path.join(EXTRACT_DIR, 'test', 'images'),
    src_labels = os.path.join(EXTRACT_DIR, 'test', 'labels'),
    dst_images = os.path.join(FINAL_DIR, 'test', 'images'),
    dst_labels = os.path.join(FINAL_DIR, 'test', 'labels'),
    prefix     = "rf_"
)
print(f"  Copied {n} Roboflow test images")

# ── STEP 7: Count totals ───────────────────────────────────────────────
train_count = len(os.listdir(os.path.join(FINAL_DIR, 'train', 'images')))
valid_count = len(os.listdir(os.path.join(FINAL_DIR, 'valid', 'images')))
test_count  = len(os.listdir(os.path.join(FINAL_DIR, 'test',  'images')))

# ── STEP 8: Write data.yaml ───────────────────────────────────────────
print("\nStep 7: Writing data.yaml...")
yaml_content = f"""# MediScan Strip Detection Dataset
# Auto-generated by merge_roboflow.py

path: {FINAL_DIR.replace(chr(92), '/')}
train: train/images
val:   valid/images
test:  test/images

nc: 1
names:
  - medicine_strip
"""
yaml_path = os.path.join(FINAL_DIR, 'data.yaml')
with open(yaml_path, 'w') as f:
    f.write(yaml_content)

# ── SUMMARY ───────────────────────────────────────────────────────────
print("\n" + "="*50)
print("MERGE COMPLETE")
print("="*50)
print(f"  Train images : {train_count}")
print(f"  Valid images : {valid_count}")
print(f"  Test  images : {test_count}")
print(f"  Total        : {train_count + valid_count + test_count}")
print(f"\n  data.yaml saved to: {yaml_path}")
print(f"\n  Ready for YOLOv8 training!")